openapi: 3.0.3
info:
  title: Media API
  version: 1.0.0

paths:
  /admin/media:
    post:
      summary: Create a media
      operationId: createMedia
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MediaCreateRequest'
      responses:
        '201':
          description: Media created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MediaCreateResponse'

components:
  schemas:
    MediaCreateRequest:
      type: object
      required:
        - name
        - release_date
      properties:
        name:
          type: string
        release_date:
          type: string
          format: date

    MediaCreateResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
