workflow:
  rules:
    - changes:
        - rag-generator/backend-springboot/**/*
    - when: never

image: maven:3.9-eclipse-temurin-21

stages:
  - install
  - test
  - build

.default-backend-springboot:
  variables:
    PROJECT_DIR: rag-generator/backend-springboot
  cache:
    key: backend-springboot
    paths:
      - $PROJECT_DIR/.m2/repository
    policy: pull-push
  artifacts:
    paths:
      - $PROJECT_DIR/.m2/repository
    expire_in: 1h

install:backend-springboot:
  stage: install
  extends: .default-backend-springboot
  script:
    - echo "Installing dependencies"
    - cd $PROJECT_DIR
    - mvn -B -DskipTests verify

test:backend-springboot:
  stage: test
  extends: .default-backend-springboot
  dependencies:
    - install:backend-springboot
  script:
    - echo "Running unit tests"
    - cd $PROJECT_DIR
    - mvn -B clean test
  artifacts:
    when: always
    reports:
      junit: $PROJECT_DIR/target/surefire-reports/*.xml
    paths:
      - $PROJECT_DIR/target/surefire-reports/

build:backend-springboot:
  stage: build
  extends: .default-backend-springboot
  dependencies:
    - install:backend-springboot
  script:
    - echo "Building Spring Boot JAR"
    - cd $PROJECT_DIR
    - mvn -B -DskipTests package
  artifacts:
    paths:
      - $PROJECT_DIR/target/*.jar
      - $PROJECT_DIR/target/*.war
    expire_in: 1 week
