name: rag-generator-backend-springboot

on:
  push:
    branches: [master]
    paths:
      - 'rag-generator/backend-springboot/**'
  pull_request:
    branches: [master]
    paths:
      - 'rag-generator/backend-springboot/**'
      
jobs:
  build-test-docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rag-generator/backend-springboot

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run unit tests
        run: mvn clean test

      - name: Generate JaCoCo report
        run: mvn jacoco:report

      - name: Build project
        run: mvn clean install

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rag-generator-backend-springboot:latest \
            -f docker/Dockerfile.backend-springboot .        

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/rag-generator-backend-springboot:latest
